// ─────────────────────────────────────────────────────────────────
// GENERATED by scripts/build-read-times.mjs — do NOT edit by hand.
//
// Prose word counts and reading times for every long-form page,
// counted from the JSX text of each module. Regenerate with:
//   npm run readtimes:build
//
// A missing entry is caught by lib/content/read-times.test.ts rather
// than by a page quietly rendering no reading time.
// ─────────────────────────────────────────────────────────────────

export type ReadTimeKind = "essay" | "research" | "case-study";

export type ReadTimeEntry = {
  /** Words of prose a reader reads, footnote bodies excluded. */
  words: number;
  /** Those words at 225 words per minute, floored at 1. */
  minutes: number;
};

export const WORDS_PER_MINUTE = 225;

export const READ_TIMES: Record<
  ReadTimeKind,
  Record<string, ReadTimeEntry>
> = {
  "case-study": {
    "architecture-under-contract": { words: 2478, minutes: 11 },
    "basecamp-coffee": { words: 2487, minutes: 11 },
    "building-this-site": { words: 5084, minutes: 23 },
    "muck-rack": { words: 2667, minutes: 12 },
    "people-inc": { words: 4218, minutes: 19 },
    "user-interviews": { words: 2056, minutes: 9 },
  },
  "essay": {
    "context-rules-everything": { words: 639, minutes: 3 },
    "growth-personalization-ai-data-primer": { words: 2093, minutes: 9 },
    "ms-in-law-data-governance": { words: 1245, minutes: 6 },
    "personalization-is-a-platform": { words: 814, minutes: 4 },
    "roadmap-to-making-better-choices": { words: 1644, minutes: 7 },
    "technically-speaking": { words: 503, minutes: 2 },
  },
  "research": {
    "ethics-video-sharing-apps": { words: 2583, minutes: 11 },
    "privacy-law-social-media-era": { words: 9521, minutes: 42 },
    "sea-level-rise-florida": { words: 897, minutes: 4 },
  },
};
