// ─────────────────────────────────────────────────────────────────
// /robots.txt — generated by Next.js App Router from this file.
//
// Public site (Landing, Resume, About, Contact, Music) is fully
// crawlable. Two paths are disallowed:
//
//   - /banner/* — these routes render LinkedIn banner export
//     artifacts, not navigational content. They already carry
//     `robots: noindex` metadata via the layout, but listing them
//     here gives search consoles the canonical signal too. Removes
//     any chance they show up in a "Malcolm Xavier" SERP.
//
//   - /api/* — internal API routes (e.g. /api/spotify/health).
//     These return JSON, not HTML, but disallowing them keeps the
//     crawl budget focused on real content.
//
//   - /*/facet-search — the three typeahead endpoints behind the
//     filter omniboxes (films, television, connected). They return
//     application/json with no navigational content, so they sit in
//     the same "don't burn crawl budget on JSON" bucket as /api/* —
//     they just live outside the /api/ prefix by route convention.
//
// Reference: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/robots
// ─────────────────────────────────────────────────────────────────

import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: [
        "/banner/",
        "/api/",
        "/films/reviews/facet-search",
        "/television/reviews/facet-search",
        "/stats/connected/facet-search",
      ],
    },
    // Point crawlers at the sitemap so they don't have to discover
    // routes by walking links. Next.js generates /sitemap.xml from
    // app/sitemap.ts.
    sitemap: "https://malxavi.com/sitemap.xml",
  };
}
