// ─────────────────────────────────────────────────────────────────
// /sitemap.xml — generated by Next.js App Router from this file.
//
// Lists the five public MVP pages so search engines have a single
// canonical source of "what's actually on this site." `app/robots.ts`
// auto-includes a reference to this sitemap, so `/robots.txt` already
// points crawlers here — no extra wiring needed.
//
// Priorities reflect funnel intent for the recruiter audience
// (primary): Landing > Resume > About > Contact > Music. Music is
// secondary content (sub-brand cluster) and lower priority for
// search ranking, but still indexable.
//
// `lastModified` is set to build-time so each deploy refreshes the
// freshness signal without us having to track per-page edit dates
// manually. Acceptable approximation for a site this size.
//
// Excluded from the sitemap (and disallowed in robots):
//   - /banner/*  — LinkedIn banner export artifacts, not navigation
//   - /api/*     — internal API routes (Spotify integration, etc.)
//
// Reference: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap
// ─────────────────────────────────────────────────────────────────

import type { MetadataRoute } from "next";

const SITE_URL = "https://malxavi.com";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  return [
    {
      url: SITE_URL,
      lastModified,
      changeFrequency: "monthly",
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/resume`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/about`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/contact`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/music`,
      lastModified,
      // Music data updates weekly via Spotify; the page itself
      // doesn't restructure, but the underlying playlists shift.
      changeFrequency: "weekly",
      priority: 0.5,
    },
  ];
}
