// ─────────────────────────────────────────────────────────────────
// /sitemap.xml — generated by Next.js App Router from this file.
//
// Lists the five public MVP pages so search engines have a single
// canonical source of "what's actually on this site." `app/robots.ts`
// auto-includes a reference to this sitemap, so `/robots.txt` already
// points crawlers here — no extra wiring needed.
//
// Priorities reflect funnel intent for the recruiter audience
// (primary): Landing > Resume > About > Contact > Music. Music is
// secondary content (sub-brand cluster) and lower priority for
// search ranking, but still indexable.
//
// `lastModified` is set to build-time so each deploy refreshes the
// freshness signal without us having to track per-page edit dates
// manually. Acceptable approximation for a site this size.
//
// Excluded from the sitemap (and disallowed in robots):
//   - /banner/*  — LinkedIn banner export artifacts, not navigation
//   - /api/*     — internal API routes (Spotify integration, etc.)
//
// Reference: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap
// ─────────────────────────────────────────────────────────────────

import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site-config";
import { getFilms } from "@/lib/feeds/letterboxd";
import { slugifyGenre as slugifyFilmGenre } from "@/lib/feeds/letterboxd-utils";
import { getShows } from "@/lib/feeds/serializd";
import { slugifyGenre as slugifyTvGenre } from "@/lib/feeds/serializd-utils";
import { CASE_STUDIES } from "@/app/resume/resume-data";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  // /films listing + every detail page + a static genre route per
  // active TMDB genre in the snapshot. Long-tail SEO depends on
  // Googlebot finding all 741 review URLs and each genre cluster;
  // explicit sitemap entries materially speed up discovery. Each
  // detail entry uses its own latestReviewDate as lastModified so
  // freshness signals reflect actual review activity.
  const filmEntries: MetadataRoute.Sitemap = [];
  try {
    const { films, summary } = getFilms();
    filmEntries.push({
      url: `${SITE_URL}/films`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.6,
    });
    // Genre routes — one per active genre. Priority sits between
    // the listing and the individual detail pages: these are the
    // long-tail entry surfaces for "malcolm xavier {genre} reviews"
    // queries, so they earn higher signal than a single review.
    for (const genre of Object.keys(summary.genreDistribution)) {
      filmEntries.push({
        url: `${SITE_URL}/films/genre/${slugifyFilmGenre(genre)}`,
        lastModified,
        changeFrequency: "weekly",
        priority: 0.55,
      });
    }
    for (const film of films) {
      filmEntries.push({
        url: `${SITE_URL}/films/${film.letterboxdSlug}-${film.releaseYear}`,
        lastModified: film.latestReviewDate
          ? new Date(film.latestReviewDate)
          : lastModified,
        changeFrequency: "yearly",
        priority: 0.5,
      });
    }
  } catch {
    // Snapshot read failure (missing fixture, malformed JSON).
    // Skip film entries rather than crash the whole sitemap; the
    // static pages below still serve. Next refresh rebuilds clean.
  }

  // /television cluster — same shape as the films block above:
  // listing + watching offshoot + every detail page + a genre
  // route per active TMDB-TV genre. Detail-page lastModified
  // uses latestActivityDate so freshness signals reflect actual
  // review activity (newer episode logs bump the show's date).
  const tvEntries: MetadataRoute.Sitemap = [];
  try {
    const { shows, summary } = getShows();
    tvEntries.push({
      url: `${SITE_URL}/television`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.6,
    });
    tvEntries.push({
      url: `${SITE_URL}/television/watching`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.55,
    });
    for (const genre of Object.keys(summary.genreDistribution)) {
      tvEntries.push({
        url: `${SITE_URL}/television/genre/${slugifyTvGenre(genre)}`,
        lastModified,
        changeFrequency: "weekly",
        priority: 0.55,
      });
    }
    for (const show of shows) {
      tvEntries.push({
        url: `${SITE_URL}/television/${show.slug}`,
        lastModified: show.latestActivityDate
          ? new Date(show.latestActivityDate)
          : lastModified,
        changeFrequency: "yearly",
        priority: 0.5,
      });
    }
  } catch {
    // Snapshot read failure — same defensive posture as the
    // films block above. Static pages still serve.
  }

  return [
    {
      url: SITE_URL,
      lastModified,
      changeFrequency: "monthly",
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/resume`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/about`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/contact`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/music`,
      lastModified,
      // Music data updates weekly via Spotify; the page itself
      // doesn't restructure, but the underlying playlists shift.
      changeFrequency: "weekly",
      priority: 0.5,
    },
    // Case studies — long-form artifacts of past work. Higher
    // priority than Music since recruiters explicitly hunt for
    // these, but lower than the core funnel pages. The index page
    // is listed explicitly; individual entries iterate CASE_STUDIES
    // from resume-data.tsx so a new case study lands in the sitemap
    // automatically without a parallel edit here.
    {
      url: `${SITE_URL}/case-studies`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    ...CASE_STUDIES.map((study) => ({
      url: `${SITE_URL}${study.href}`,
      lastModified,
      // Work case studies are presumed stable once shipped (the work
      // itself doesn't iterate); the meta "building-this-site" study
      // updates with the portfolio. "monthly" reads honestly across
      // both shapes without forcing a per-entry override.
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
    ...filmEntries,
    ...tvEntries,
  ];
}
