// ─────────────────────────────────────────────────────────────────
// /sitemap.xml — generated by Next.js App Router from this file.
//
// Lists the five public MVP pages so search engines have a single
// canonical source of "what's actually on this site." `app/robots.ts`
// auto-includes a reference to this sitemap, so `/robots.txt` already
// points crawlers here — no extra wiring needed.
//
// Priorities reflect funnel intent for the recruiter audience
// (primary): Landing > Resume > About > Contact > Music. Music is
// secondary content (sub-brand cluster) and lower priority for
// search ranking, but still indexable.
//
// `lastModified` is set to build-time so each deploy refreshes the
// freshness signal without us having to track per-page edit dates
// manually. Acceptable approximation for a site this size.
//
// Excluded from the sitemap (and disallowed in robots):
//   - /banner/*  — LinkedIn banner export artifacts, not navigation
//   - /api/*     — internal API routes (Spotify integration, etc.)
//
// Reference: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap
// ─────────────────────────────────────────────────────────────────

import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site-config";
import { getFilms } from "@/lib/feeds/letterboxd";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  // /films listing + every detail page. Long-tail SEO depends on
  // Googlebot finding all 741 review URLs; the listing is now an
  // internal-link target from the / matrix tile, so crawl-discovery
  // would eventually find them, but explicit sitemap entries
  // materially speed it up. Each detail entry uses its own
  // latestReviewDate as lastModified so freshness signals reflect
  // actual review activity. Closes films-listing-not-in-sitemap.
  const filmEntries: MetadataRoute.Sitemap = [];
  try {
    const { films } = getFilms();
    filmEntries.push({
      url: `${SITE_URL}/films`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.6,
    });
    for (const film of films) {
      filmEntries.push({
        url: `${SITE_URL}/films/${film.letterboxdSlug}-${film.releaseYear}`,
        lastModified: film.latestReviewDate
          ? new Date(film.latestReviewDate)
          : lastModified,
        changeFrequency: "yearly",
        priority: 0.5,
      });
    }
  } catch {
    // Snapshot read failure (missing fixture, malformed JSON).
    // Skip film entries rather than crash the whole sitemap; the
    // static pages below still serve. Next refresh rebuilds clean.
  }

  return [
    {
      url: SITE_URL,
      lastModified,
      changeFrequency: "monthly",
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/resume`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/about`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/contact`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/music`,
      lastModified,
      // Music data updates weekly via Spotify; the page itself
      // doesn't restructure, but the underlying playlists shift.
      changeFrequency: "weekly",
      priority: 0.5,
    },
    // Case studies — long-form artifacts of past work. Higher
    // priority than Music since recruiters explicitly hunt for
    // these, but lower than the core funnel pages.
    {
      // Index page listing all case studies. Same priority as the
      // individual studies so crawlers treat it as part of the
      // long-form cluster, not a higher-tier funnel page.
      url: `${SITE_URL}/case-studies`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/case-studies/basecamp-coffee`,
      lastModified,
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/case-studies/building-this-site`,
      lastModified,
      // Meta case study about shipping the portfolio with Claude
      // Code. Updates as the portfolio itself does, so monthly
      // freshness reads more honestly than "yearly".
      changeFrequency: "monthly",
      priority: 0.7,
    },
    ...filmEntries,
  ];
}
